// static/lost-transcript-mining/viz/src/components/BarChart.vue
<template>
	<div>
		<h1>Bar bro</h1>
		<svg
			:width="width"
			:height="height"
		>
			<g
				:style="{
					transform: `translate(${margin.left}px, ${margin.top}px)`
				}
			">
				<g class="bars"></g>
			</g>
		</svg>
	</div>
</template>

<script>
import * as d3 from 'd3'

export default {
	name: 'bar-chart',
	props: {
		margin: {
			type: Object,
			default: () => ({
				left: 0,
				right: 0,
				top: 10,
				bottom: 10,
			})
		},
		width: {
			type: Number,
			default: () => 960
		},
		height: {
			type: Number,
			default: () => 500
		},
		data: {
			type: Array,
			default: () => [
				{name: 'fak', val: 5},
				{name: 'fafe', val: 3},
				{name: 'gege', val: 16},
			]
		}
	},
	data: function() {
		const {
			width,
			height,
			margin
		} = this;

		return {
			chartWidth: width - margin.left - margin.right,
			chartHeight: height - margin-top - margin.bottom
		}
	},
	mounted() {
		this.init()
	},
	methods: {
		init() {
			const {
				width,
				height,
				data
			} = this
			var x = d3.scaleBand()
			          .range([0, width])
			          .padding(0.1);
			var y = d3.scaleLinear()
			          .range([height, 0]);

		  // Scale the range of the data in the domains
		  x.domain(data.map(function(d) { return d.name; }));
		  y.domain([0, d3.max(data, function(d) { return d.val; })]);

			  d3.select('.bars').selectAll(".bar")
			      .data(this.data)
			    .enter().append("rect")
			      .attr("class", "bar")
			      .attr("x", function(d) { return x(d.name); })
			      .attr("width", x.bandwidth())
			      .attr("y", function(d) { return y(d.val); })
			      .attr("height", function(d) { return height - y(d.val); });

		}
	}
}
</script>

<style>
.bar {
	fill: steelblue;
}
</style>

// static/lost-transcript-mining/viz2/src/components/BarChart/BarChart.jsx
import React, { Component } from 'react'
import * as d3 from 'd3'

import { Axis } from '../'

import style from './BarChart.css'

export default class BarChart extends Component {
	static defaultProps = {
		width: 480,
		height: 500,
		padding: {
			top: 0,
			right: 0,
			bottom: 0,
			left: 0,
		},
		data: [
			{key: 'JACK', value: 134},
			{key: 'KATE', value: 1121},
			{key: 'QAYT', value: 821},
			{key: 'JACQUEAUIAZXAUQX', value: 314},
		]
	}

	state = {
		linearScale: d3.scaleLinear(),
		bandScale: d3.scaleBand(),
	}

	componentWillReceiveProps({ data, width, height, padding }) {
		console.log('recalc')
		const linearScale = d3.scaleLinear()
		.range([height - padding.top - padding.bottom, 0])
		.domain([0, d3.max(data, d => d.value)])

		const bandScale = d3.scaleBand()
		.range([0, width - padding.right - padding.left])
		.padding(0.1)
		.domain(data.map(d => d.key))

		this.setState({
			linearScale,
			bandScale
		})
	}

	render() {
		const {
			width,
			height,
			padding,
			data
		} = this.props

		const {
			linearScale,
			bandScale
		} = this.state

		return (
			<svg
				width={width}
				height={height}
			>
				<g
					transform={`translate(${padding.left}, ${padding.top})`}
				>
					<Axis
						orientation="left"
						scale={linearScale}
						tickSize={-width + padding.right + padding.left}
						className={style.yAxis}
					/>
					<Axis
						orientation="bottom"
						scale={bandScale}
						tickSize={3}
						className={style.xAxis}
						transform={`translate(0, ${height - padding.top - padding.bottom})`}
					/>
					<g>
						{data.map(({ key, value }) =>
							<rect
								x={bandScale(key)}
								y={linearScale(value)}
								width={bandScale.bandwidth()}
								height={height - padding.top - padding.bottom - linearScale(value)}
								className={style.bar}
								key={key}
							/>
						)}
					</g>
				</g>
			</svg>
		)
	}
}
